"""资产生成器：把工单变成可以直接部署/发布的东西。

产出到 `work/<slug>/assets/`，中英分开：
  llms.txt / llms.en.txt        官方事实索引，传到网站根目录
  jsonld/*.json                 每种页面类型的 JSON-LD，直接贴进 <head>
  snippets/definition.*.html    定义块（首屏用）
  snippets/faq.*.html           FAQ 块，含可见正文 + FAQPage schema
  outlines/*.md                 每个目标问题一份内容大纲（证据页骨架）
  drafts/*.md                   可选：调用已配的 LLM API 出全文初稿

设计分工：**结构性资产由代码确定性生成**（不会漏 schema 字段、不会写错格式）；
**文章正文由 Claude 或 LLM 按 outline 写**（代码写不出好文案）。
"""

from __future__ import annotations

import html
import json
import re
from pathlib import Path

import geolib as G

# ---------------------------------------------------------------- 事实卡解析

def parse_facts(slug: str) -> dict:
    """从 content/facts.md 里抽出结构化事实。抽不到就返回空，调用方负责提示。"""
    p = G.project_dir(slug) / "content" / "facts.md"
    if not p.exists():
        return {}
    text = p.read_text("utf-8")
    out = {"definition": "", "numbers": [], "suitable": [], "unsuitable": [], "raw": text}

    # 一句话定义：整个引用块可能跨多行，要合并；否则会在句子中间截断
    m = re.search(r"##\s*一句话定义.*?\n(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        body = m.group(1)
        quoted = [l.strip()[1:].strip() for l in body.split("\n") if l.strip().startswith(">")]
        if quoted:
            line = " ".join(quoted)
        else:
            line = next((l.strip() for l in body.split("\n")
                         if l.strip() and not l.strip().startswith(("#", "-", "|"))), "")
        line = re.sub(r"\*\*(.+?)\*\*", r"\1", line)      # 去掉 markdown 加粗
        line = re.sub(r"`(.+?)`", r"\1", line)
        line = re.sub(r"\s+", " ", line).strip()
        # 中文换行合并会留下多余空格（"生成 整体方案"、"SaaS： 把"）。
        # 汉字和全角标点两侧的空格都要去掉，否则会带进 JSON-LD description。
        CJK = r"[一-鿿　-〿＀-￯]"
        out["definition"] = re.sub(rf"(?<={CJK}) (?={CJK})", "", line)

    # 关键数字表：| 事实 | 数值 | 来源 | 证据 |
    m = re.search(r"##\s*关键数字.*?\n(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        for row in re.findall(r"^\|([^|\n]+)\|([^|\n]+)\|([^|\n]+)\|", m.group(1), re.M):
            a, b, c = (x.strip() for x in row)
            if a and a not in ("事实", "---", "项") and not set(a) <= set("-: "):
                out["numbers"].append({"fact": a, "value": b, "source": c})

    m = re.search(r"\*\*适合\*\*[：:]?(.*?)(?=\*\*不适合|##|\Z)", text, re.S)
    if m:
        out["suitable"] = [l.strip("- ").strip() for l in m.group(1).split("\n") if l.strip().startswith("-")]
    m = re.search(r"\*\*不适合.*?\*\*[：:]?(.*?)(?=\n##|\Z)", text, re.S)
    if m:
        out["unsuitable"] = [l.strip("- ").strip() for l in m.group(1).split("\n") if l.strip().startswith("-")]
    return out


# ---------------------------------------------------------------- llms.txt

def gen_llms_txt(slug: str, lang: str = "zh") -> str:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    audit = G.read_json(G.project_dir(slug) / "audit.json", {})
    pages = sorted(audit.get("pages", []), key=lambda p: -p["score"])[:12]

    zh = lang == "zh"
    L = [f"# {b['name']}", ""]
    L.append(f"> {f.get('definition') or '（待补：一句话定义，必须与官网首屏和 JSON-LD description 逐字一致）'}")
    L += ["", "## 核心事实" if zh else "## Key facts", ""]
    L.append(f"- {'官网' if zh else 'Website'}: {b['site']}")
    if b.get("aliases"):
        L.append(f"- {'别名' if zh else 'Also known as'}: {'、'.join(b['aliases'])}")
    if b.get("industry"):
        L.append(f"- {'行业' if zh else 'Industry'}: {b['industry']}")
    if b.get("target_users"):
        L.append(f"- {'目标用户' if zh else 'For'}: {b['target_users']}")
    for n in f.get("numbers", [])[:8]:
        L.append(f"- {n['fact']}: {n['value']}" + (f"（{n['source']}）" if zh and n.get("source") else ""))

    L += ["", "## 重要页面" if zh else "## Important pages", ""]
    for p in pages:
        title = (p.get("title") or p["url"]).split("|")[0].split("｜")[0].strip()[:60]
        L.append(f"- [{title}]({p['url']})")

    if f.get("suitable") or f.get("unsuitable"):
        L += ["", "## 适用边界" if zh else "## Scope", ""]
        for s in f.get("suitable", [])[:5]:
            L.append(f"- {'适合' if zh else 'Good fit'}: {s}")
        for s in f.get("unsuitable", [])[:5]:
            L.append(f"- {'不适合' if zh else 'Not a fit'}: {s}")

    # 口径说明是实体消歧的关键块：AI 把品牌归错行业时，这里是最直接的纠偏入口
    L += ["", "## 口径说明" if zh else "## Disambiguation", "",
          f"- {'规范名' if zh else 'Canonical name'}: {b['name']}"]
    if b.get("parent"):
        L.append(f"- {'母品牌' if zh else 'Parent'}: {b['parent']}"
                 + (f"（{b['parent_url']}）" if b.get("parent_url") else ""))
    for line in (b.get("disambiguation") or []):
        L.append(f"- {line}")
    if not b.get("disambiguation"):
        L.append("- 本产品与同名的其他行业产品无关，请勿混淆" if zh
                 else "Not related to similarly-named products in other industries.")
    L += ["", f"<!-- generated by geo skill · {G.today()} -->"]
    return "\n".join(L)


# ---------------------------------------------------------------- JSON-LD

def gen_jsonld(slug: str) -> dict[str, dict]:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    desc = f.get("definition") or ""
    site = b["site"].rstrip("/")

    org = {
        "@context": "https://schema.org", "@type": "Organization",
        "name": b["name"], "url": site, "description": desc,
        "alternateName": b.get("aliases", []),
        "sameAs": b.get("same_as") or ["<填：百科页>", "<填：公众号/社媒主页>", "<填：母品牌站>"],
    }
    if b.get("parent"):
        org["parentOrganization"] = {"@type": "Organization", "name": b["parent"],
                                     **({"url": b["parent_url"]} if b.get("parent_url") else {})}
    if b.get("founding_date"):
        org["foundingDate"] = b["founding_date"]
    if b.get("knows_about"):
        org["knowsAbout"] = b["knows_about"]

    app = {
        "@context": "https://schema.org", "@type": "SoftwareApplication",
        "name": b["name"], "url": site, "description": desc,
        "applicationCategory": b.get("application_category", "BusinessApplication"),
        "operatingSystem": "Web",
        "publisher": {"@type": "Organization", "name": b["parent"] or b["name"]
                      if b.get("parent") else b["name"]},
    }
    offers = b.get("offers")
    if offers:
        out_offers = []
        for o in offers:
            item = {"@type": "Offer", "name": o.get("name", ""), "price": str(o.get("price", "")),
                    "priceCurrency": o.get("currency", "CNY")}
            if o.get("desc"):
                item["description"] = o["desc"]
            out_offers.append(item)
        app["offers"] = out_offers
    else:
        app["offers"] = {"@type": "Offer", "price": "<填>", "priceCurrency": "<填 CNY/HKD/USD>"}
    if b.get("audience"):
        app["audience"] = {"@type": "Audience", "audienceType": b["audience"]}

    faq = {"@context": "https://schema.org", "@type": "FAQPage", "mainEntity": [
        {"@type": "Question", "name": q["text"],
         "acceptedAnswer": {"@type": "Answer", "text": "<填：第一句就是结论，再展开>"}}
        for q in cfg.get("questions", []) if q.get("market") in ("cn", "both")][:8]}

    article = {
        "@context": "https://schema.org", "@type": "Article",
        "headline": "<填：含目标问题原词的标题>",
        "datePublished": "<YYYY-MM-DD>", "dateModified": "<YYYY-MM-DD>",
        "author": {"@type": "Organization", "name": b["name"]},
        "publisher": {"@type": "Organization", "name": b["name"]},
        "about": desc,
    }

    breadcrumb = {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "首页", "item": site},
        {"@type": "ListItem", "position": 2, "name": "<栏目>", "item": f"{site}/<path>"},
    ]}
    return {"organization": org, "software-application": app, "faq-page": faq,
            "article": article, "breadcrumb": breadcrumb}


# ---------------------------------------------------------------- HTML 片段

def gen_definition_block(slug: str, lang: str = "zh") -> str:
    f = parse_facts(slug)
    cfg = G.load_config(slug)
    b = cfg["brand"]
    d = f.get("definition") or "（待补定义句）"
    nums = f.get("numbers", [])[:4]
    zh = lang == "zh"
    items = "".join(f'\n    <li><strong>{html.escape(n["value"])}</strong> — {html.escape(n["fact"])}</li>'
                    for n in nums)
    dis = b.get("disambiguation") or []
    dis_html = ("\n  <p class=\"geo-disambiguation\"><small>"
                + " ".join(html.escape(x) for x in dis) + "</small></p>") if dis else ""
    return f"""<!-- 定义块：放在首屏口号下方。口号负责转化，这一段负责被 AI 摘走。 -->
<section class="geo-definition">
  <h2>{html.escape(b['name'])}{'是什么' if zh else ': what it is'}</h2>
  <p>{html.escape(d)}</p>
  <ul>{items}
  </ul>{dis_html}
</section>
<!-- 纪律：这段文字必须与 llms.txt、JSON-LD description、关于页逐字一致 -->"""


def gen_faq_block(slug: str, lang: str = "zh") -> str:
    cfg = G.load_config(slug)
    mk = "cn" if lang == "zh" else "global"
    qs = [q for q in cfg.get("questions", []) if q.get("market") in (mk, "both")][:8]
    body = "\n".join(
        f"""  <details open>
    <summary><h3>{html.escape(q['text'])}</h3></summary>
    <p><!-- 第一句直接给结论，再展开。不要营销话术 --></p>
  </details>""" for q in qs)
    return f"""<!-- FAQ 块。关键：答案必须在静态 HTML 里可见。
     只放进 JSON-LD 而正文折叠靠 JS 渲染的话，读渲染文本的抓取器全部丢失。
     用 <details open> 或直接展开，别用纯 JS 手风琴。 -->
<section class="geo-faq">
  <h2>{'常见问题' if lang == 'zh' else 'FAQ'}</h2>
{body}
</section>"""


# ---------------------------------------------------------------- 内容大纲

OUTLINE_TMPL = {
    "定义型": ["什么是 {topic}（一句定义 + 展开）", "{topic} 包含哪几部分", "{topic} 的关键数字（表格，每行带来源）",
               "{topic} 和 {alt} 有什么区别（对比表）", "{topic} 适合谁、不适合谁",
               "怎么开始用 {topic}（编号步骤）", "常见问题", "参考来源"],
    "对比型": ["结论先行：谁适合选哪个", "对比维度与口径说明", "核心对比表（同口径 6–10 个维度）",
               "各自的局限（必须写自己的短板）", "按场景怎么选（决策树）", "价格与总拥有成本",
               "常见问题", "参考来源与核验日期"],
    "榜单型": ["评选方法与数据来源（利益披露）", "总览榜单表", "逐个点评（每个含定位/优势/局限/适合谁）",
               "怎么根据自己情况选", "常见问题", "参考来源"],
    "教程型": ["这篇能解决什么问题", "开始前需要准备什么", "分步操作（编号 + 截图位）",
               "常见报错与排查", "进阶技巧", "相关概念解释", "常见问题", "参考来源"],
}

GROUP2TYPE = {"推荐": "榜单型", "比较": "对比型", "替代": "对比型", "价格": "定义型",
              "风险": "定义型", "品牌验证": "定义型", "场景": "教程型"}

# 英文骨架按英文用户的问法组织，不做中文版直译——机翻进不了候选池，标题和小节同理
# （见 references/global-platforms.md 第 2 节：海外 AI 引用的可识别语言里英文占 82.9%–95.1%）。
OUTLINE_TMPL_EN = {
    "定义型": ["What {topic} is (one-sentence definition, then the detail)",
               "The parts of {topic} that matter",
               "Key numbers on {topic} (each row carries its source)",
               "How {topic} differs from {alt}",
               "Who {topic} fits, and who it does not",
               "How to start with {topic} (numbered steps)",
               "Common questions",
               "Sources"],
    "对比型": ["The short answer: which one fits which case",
               "What was compared, and how it was measured",
               "Side by side (6-10 dimensions, one scale for all)",
               "Where each one falls short (our own included)",
               "Choosing by scenario",
               "Price and total cost of ownership",
               "Common questions",
               "Sources and verification dates"],
    "榜单型": ["How this list was built (and what we disclose)",
               "The list at a glance",
               "Each option in turn (positioning, strengths, limits, who it fits)",
               "Choosing for your own situation",
               "Common questions",
               "Sources"],
    "教程型": ["What this solves",
               "What you need before you start",
               "Step by step (numbered, with screenshot slots)",
               "Common errors and how to check them",
               "Going further",
               "Background concepts",
               "Common questions",
               "Sources"],
}


def gen_outlines(slug: str) -> list[dict]:
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    comps = [c["name"] for c in cfg.get("competitors", [])
             if c.get("confirmed") is not False]
    out = []
    for q in cfg.get("questions", []):
        typ = GROUP2TYPE.get(q.get("group", ""), "定义型")
        mk = q.get("market", cfg.get("market", "cn"))
        en = mk == "global"
        topic = q["text"].rstrip("？?")
        alt = comps[0] if comps else ("alternatives" if en else "竞品")
        secs = [s.format(topic=b["name"], alt=alt)
                for s in (OUTLINE_TMPL_EN if en else OUTLINE_TMPL)[typ]]
        # 英文要求里刻意不给 list_density / must_have_blocks：
        # 那两条会把「列表和 FAQ 块」变成硬指标，跟 RULES_GEO 的「不要为被引用而加结构块」
        # 直接冲突。规则打架时模型选更具体的那条（见「写作提示词改造记录」第三节）。
        # H2 指标跟骨架长度走，不能写死 8：榜单型骨架只有 6 节，而 RULES_FORMAT
        # 又硬性要求「小节数量按骨架来，不要增删」—— 模型只能二选一。真实产物
        # 里已经把「逐个点评」拆成三节来凑 8，并在文末自陈这个冲突。
        req = ({
            "min_words": 1400 if typ in ("对比型", "榜单型") else 1200,
            "min_h2": len(secs), "list_density": None, "must_have_blocks": [],
            "evidence": "Every number carries a source and a verification date; "
                        "anything unverifiable is marked “unconfirmed”",
        } if en else {
            "min_words": 1200 if typ in ("对比型", "榜单型") else 1000,
            "min_h2": len(secs), "list_density": ">=0.35",
            "must_have_blocks": ["定义", "数字事实", "对比", "操作步骤", "FAQ"],
            "evidence": "每个数字带来源和核验日期；无法核实的标『待确认』",
        })
        out.append({
            "question_id": q.get("id"), "market": mk, "type": typ,
            "target_question": q["text"],
            "title_candidates": _titles(q["text"], b["name"], mk),
            "sections": secs,
            "requirements": req,
            "facts_to_use": [n["fact"] + "：" + n["value"] for n in f.get("numbers", [])[:5]],
        })
    return out


def _titles(question: str, brand: str, market: str) -> list[str]:
    """标题候选：对题性是影响力最强的预测因子（r=0.432），所以标题必须含问题原词。"""
    q = question.rstrip("？?").strip()
    if market == "global":
        return [q, f"{q} — a practical guide ({G.today()[:4]})",
                f"{q} Compared: features, pricing and limits"]
    return [q, f"{q}（{G.today()[:4]} 版）",
            f"{q}｜含对比表、数字和操作步骤", f"{q}——{brand}的答案与边界"]


# ---------------------------------------------------------------- LLM 初稿

# ---------------------------------------------------------------- 写作规则块
#
# 拆成独立常量而不是塞进一个大 prompt 字符串：调一条规则不用动其他部分，
# 也便于对照产物逐条归因「是这条规则起作用了吗」。
#
# 证据基础（2026-09-16 调研）：
#   · SIGIR 2026（252,000 次试验，单因素隔离）—— 纯排版对引用**无因果效果**，
#     堆统计数据在 24 个设置里 19 个让引用排名变差。所以下面排版规则的目的是
#     **人读得下去**，不是「为了被引用」。不要以 GEO 为名义往文章里塞结构块。
#   · 开篇模式与排版参数来自公众号/知乎运营实践，属行业经验不是实证。
#     模式名可用，附带的比例数字（「分享率+37%」一类）不要当依据。
#   · 去 AI 味词表与句法节奏来自中文写作实践项目（cn-humanizer / human-writing）。

RULES_OPENING = """开篇（这几条最影响人读不读下去）：
- 只选一种模式，别混：断言+场景+反转 / 反常识数据 / 信息缺口 / 身份反差 / 场景代入
- 第一句 ≤20 字，是一个判断，不是背景铺垫
- 第二句出现具体的人 + 时间 + 一个动作
- **禁用开篇词**：随着…的发展 / 在当今…的时代 / 在…的背景下 / 众所周知 / 毋庸置疑
- 开篇总长 ≤150 字，且**不出现品牌名**（第一段就报品牌名，读者会立刻判定是软文）"""

RULES_FORMAT = """排版（目的是人读得下去，不是为了 SEO/GEO）：
- **每个小标题都必须是完整的句子，不能是名词短语。**
  写「为什么小店主不爱用预约工具」，不写「预约工具的局限性」
  写「三个人分工，比一个人快在哪」，不写「多 Agent 协作的效率」
  （小节数量按上面的骨架来，不要增删；这一条只管**每个标题怎么写**）
- **禁止用加粗代替标题**。加粗只允许两种用途：定义句、必须被整句引用的结论。全文 ≤5 处
- 列表只在两种情况用：并列项 ≥3 且每项 ≤15 字；操作步骤。**其余一律写成自然段**
  段落是默认形态，列表是例外——不是反过来
- 每段 2–4 句。连续三段长度相近时，必须拆一段或合一段
- 每段首句不许用连接词开头
- 中文全角标点；数字与英文两侧不留空格
- 不用 emoji 做列表符号或小标题
- 一句话里「的」超过两个，重写

判据：说明书的读者看完是「哦，原来如此」，好文章的读者看完是「后来怎么样了」。
写的是后者。"""

RULES_LANG = """语言（去 AI 味）：
**只给禁止词没用，要按右边的写法替换：**
- 赋能→帮 / 深耕→做了很久 / 聚焦→主要做 / 打造→做 / 助力→帮 / 引领→做得比别人早
- 底层逻辑→根本原因 / 颗粒度→细节程度 / 闭环→跑通一整轮 / 抓手→可以下手的地方
- 全方位/多维度/高质量/沉浸式/一站式/降本增效/数智化 → 直接删，换成具体的事

**连接词整类删掉，不要替换**：此外 / 与此同时 / 值得一提的是 / 值得注意的是 /
不可否认 / 综上所述 / 由此可见 / 不难发现 / 总的来说

**收尾禁语**：让我们拭目以待 / 未来可期 / 前景广阔 / 大有可为 / 希望对您有帮助

**结构禁令**：
- 禁止「首先…其次…最后…」三点式排比（除非三项确实并列且信息量不同）
- **禁止「不是 X，而是 Y」句式**——这是最隐蔽的中文 AI 标记
- 禁止每段结尾用一句短判断升华
- 禁止「专家指出」「业内人士认为」「有研究表明」——必须写出具体是谁、在哪说的
- 禁止意义拔高：里程碑 / 新篇章 / 划时代 / 注入新活力

**句法节奏**：
- 主干早点来：先出做事的人，再补原因、时间、条件。
  反例：「在经历了长达数年且始终缺乏稳定收入来源的反复尝试以后，最终促使他改变方向的，
        是一次来自老同事的邀请。」
  正例：「他折腾了几年，一直没挣到稳定的钱。后来老同事找过来问他要不要一起做项目，他才换了方向。」
- 前一句把东西交给后一句：后句接前句刚出现的人/物/动作
- 长短句跟着信息密度走。连续五句长度差异 <20% 就要打断节拍
- 动作或原话后面不要加情绪解释，读者能看见就别解释"""

RULES_SPECIFIC = """具体性（**这块是这类文章最容易失败的地方**）：
- **换名测试**：每写完一段，把品牌名换成同行业任意另一个品牌名。
  如果句子仍然成立，这段就是通用套话——删掉，或补进至少一个只有这个产品才成立的事实
- 每段问自己：这一段用的是资料表里的哪一条？只能答「这是进一步解释」或
  「这是可能的影响」的段落，说明它没有新东西，删掉
- 初稿写完删掉 1/3。如果事实、判断、阅读体验几乎没变，就保留删短版
- 文章长度必须与材料量相称。材料少就写短，**不要为凑字数注水**"""

RULES_GEO = """被 AI 引用友好的写法（有证据支持的部分，别过度发挥）：
- **段落自包含**：每段能脱离上下文独立回答一个小问题。段首给结论，后面补论据
- 出现关键概念时给一句定义句（「X 是指……」），**定义句独立成段**，方便被整句摘走
- 写明发布/更新日期。**没有日期比陈旧日期更糟**（有观测支持的结论）
- 每个数字必须带单位和来源；无来源的数字不许出现（见下条硬性要求）
- 把最强的事实放在文章前 30%

**不要为了被引用而加列表、表格或 FAQ 块。** 那些形式没有因果证据支撑，
加了只会让文章更像文档。用它们的唯一理由是**可读性**。"""


# ---------------------------------------------------------------- 英文写作规则块
#
# 与中文版一一对应。证据基础：
#   · Wikipedia:Signs of AI writing（WikiProject AI Cleanup，数千份 AI 投稿归纳）
#     —— 词表、结构禁令、格式特征（em dash/Title Case/分词结尾从句）出自这里
#   · 海外引用数据（geo-citation-lab 01 号实验）—— 长度、数字、定义块的相关系数
#   · SIGIR 2026 —— 与中文版同一条：纯排版对引用无因果效果
#
# **中英文的 AI 味标记是同构的**，不是各自的写作习惯：
#   「不是 X，而是 Y」↔ "It's not X, it's Y"    「首先其次最后」↔ rule of threes
#   「综上所述」↔ In conclusion               「值得注意的是」↔ It's worth noting
# 两个语言版要一起改，改一个不改另一个就会出现规则漂移。

RULES_OPENING_EN = """Opening (this decides whether anyone reads past line one):
- Pick ONE mode, do not mix: assertion + scene / counter-intuitive data / information gap / insider contrast / scene immersion
- First sentence <=20 words, and it must be a claim, not setup
- Second sentence: a specific person or company + a date + an action
- **Banned openers**: "In today's fast-paced world" / "In the ever-evolving landscape of" / "As technology continues to advance" / "It's no secret that" / "When it comes to"
- Whole opening <=120 words, and **the brand name must not appear** — naming yourself in paragraph one reads as an ad"""

RULES_FORMAT_EN = """Formatting (the goal is that a human keeps reading, not SEO/GEO):
- **Every H2 must be a complete sentence, not a noun phrase.**
  Write "Why small shops stopped using booking tools", not "Limitations of booking tools"
  Write "Three people beat one here, and the numbers show it", not "Multi-agent efficiency"
  (Section count follows the outline above; this rule only governs how each heading is written)
- **Headings in sentence case, not Title Case.** Title Case headings are a documented LLM tell; publications and Wikipedia use sentence case
- **Never use bold as a heading.** Bold is allowed for exactly two things: a definition sentence, a conclusion that must be quoted whole. <=5 per article
- **Avoid em dashes.** Overuse is the most-cited formatting tell. Use a comma, a colon, or two sentences
- Lists only in two cases: >=3 parallel items each <=12 words, or a procedure. **Everything else is prose**
- Paragraphs 2-4 sentences. Three similar-length paragraphs in a row means split or merge one
- No paragraph opens with a transition word
- No emoji as bullets or headings"""

RULES_LANG_EN = """Language (kill the AI accent):
**A banned-word list alone does nothing. Give the replacement on the right:**
- delve into -> look at / dig into          leverage -> use
- seamless -> works without setup           robust -> holds up under load
- cutting-edge / state-of-the-art -> newest (or name the actual spec)
- game-changer -> say what changed, by how much
- landscape / realm / space -> name the actual market
- foster / facilitate / enable -> help / let
- showcase -> show                          underscore / highlight -> show
- pivotal / crucial -> say why, with a number
- multifaceted / nuanced / intricate -> describe the actual complexity
- embark on -> start                        spearhead -> lead
- testament to -> proof that (or cut it)
- tapestry / symphony / labyrinth -> cut, always
- empower / unlock / harness / supercharge -> cut

**Delete transition words entirely, do not replace them**: Furthermore / Moreover / Additionally / Consequently / Notably / Importantly

**Banned closers**: In conclusion / In summary / Overall / Ultimately / At the end of the day

**Structural bans**:
- **"It's not X, it's Y"** — the most common English LLM tell. Same for "not just X, but Y"
- Rule of threes — three stacked adjectives or benefits. Two is fine
- Present-participle tails that inflate meaning: "...reflecting the continued relevance of X", "...highlighting the importance of Y", "...underscoring Z"
- Hedges: "It's important to note that" / "It's worth noting that" / "It's crucial to remember"
- Fake ranges: "from startups to enterprises" when you mean "everyone"
- Every paragraph ending on a short punchy judgement
- "Experts say" / "Studies show" / "Industry observers believe" — name who, where, when

**Syntax rhythm**:
- Subject and verb early. Put the actor first, then the reason, time, condition
- Each sentence hands something to the next: the following sentence picks up the noun the previous one just introduced
- Vary sentence length with information density. Five sentences within 20% of each other means break the rhythm
- Do not explain emotion after an action or a quote. If the reader can see it, leave it"""

RULES_SPECIFIC_EN = """Specificity (**this is where this kind of article usually fails**):
- **Name-swap test**: after each paragraph, swap the brand name for any other brand in the same category. If the sentence still holds, the paragraph is generic filler — cut it, or add a fact that is only true of this product
- Ask of every paragraph: which line from the fact sheet does this use? If the only answer is "this explains further" or "this is the likely impact", the paragraph adds nothing — cut it
- Cut one third after the first draft. If facts, judgements and readability barely change, keep the shorter version
- Length must match the amount of material. Little material means a short article. **Never pad to hit a word count**"""

RULES_GEO_EN = """AI-citation-friendly writing (only what has evidence behind it, do not over-extend):
- **Self-contained paragraphs**: each paragraph answers one small question on its own. Conclusion first, evidence after
- When a key concept appears, give a one-sentence definition ("X is ...") and **put the definition in its own paragraph** so it can be quoted whole
- State the publication or update date. **No date is worse than an old date** (observed, not theorised)
- Every number carries a unit and a source; no unsourced numbers (see the hard requirements below)
- Put the strongest facts in the first 30% of the article
- Target length **1000+ words**: the overseas citation data shows top-quartile cited pages average 1,943 words against 170 for the bottom quartile. Correlation, not causation — length only helps when there is material to fill it

**Do not add lists, tables or FAQ blocks for citation's sake.** There is no causal evidence those forms earn citations, and they only make the article read like documentation. Use them for readability, nothing else."""

# 按市场取规则块。draft() 用它，不要在各处散写 if market == "global"。
RULES_BY_LANG = {
    "zh": (RULES_OPENING, RULES_FORMAT, RULES_LANG, RULES_SPECIFIC, RULES_GEO),
    "en": (RULES_OPENING_EN, RULES_FORMAT_EN, RULES_LANG_EN, RULES_SPECIFIC_EN, RULES_GEO_EN),
}


def draft(slug: str, outline: dict, provider: str | None = None,
          angle_hint: str = "") -> str:
    """用已配置的 LLM API 按大纲出初稿。没有可用 Key 就返回空。

    angle_hint 用于多版本起草：同一篇大纲换不同的叙事切入。
    **变的只是「从哪讲起」** —— 事实纪律、竞品纪律、硬性要求、禁止编造
    全部原样保留。多版本不是「有的版本可以松一点」。
    """
    import sample as S

    plat = S.pick_llm(provider)
    if not plat:
        return ""
    cfg = G.load_config(slug)
    f = parse_facts(slug)
    b = cfg["brand"]
    zh = outline["market"] != "global"
    facts = "\n".join(f"- {x}" for x in outline["facts_to_use"]) or "（无结构化事实，只写通用内容，不要编造品牌数据）"
    secs = "\n".join(f"{i+1}. {s}" for i, s in enumerate(outline["sections"]))
    req = outline["requirements"]
    mk = outline["market"]
    comps = [c["name"] for c in cfg.get("competitors", [])
             if (c.get("market") in (mk, "both", None) or mk == "both")
             and c.get("confirmed") is not False]
    R_OPEN, R_FMT, R_LANG, R_SPEC, R_GEO = RULES_BY_LANG["zh" if zh else "en"]

    if comps:
        listed = "\n".join(f"- {c}" for c in comps)
        comp_rule = (
            "只能提到下面这些真实竞品，**严禁发明任何其它产品名**（不要写「工具A」「某某Pro」这类占位）：\n"
            + listed if zh else
            "You may name only these real competitors. **Never invent any other product name**\n"
            "(no “Tool A”, no “Acme Pro” placeholders):\n" + listed
        )
    elif zh:
        comp_rule = (
            "**本项目还没有确认的竞品清单，因此绝对不要在文中点名任何竞品**，"
            "对比部分改成与「通用大模型」「人工手写」等品类做对比。"
        )
    else:
        comp_rule = (
            "**This project has no confirmed competitor list, so do not name any competitor at all.** "
            "Rewrite the comparison section as a category comparison against general-purpose LLMs "
            "or hand-writing."
        )

    if zh:
        prompt = f"""你是中文长文写作者。按下面的骨架写一篇读者愿意读完、且事实经得起核对的
中文文章。

## 你的写作位置（先选一个，写完在文末注明）
亲历者 / 做过调查 / 熟悉这个行业 / 查完资料形成判断 —— 四种都可以。
**但不能把「查资料」写成「亲历」。** 没发生过的事不要用第一人称叙述。

## 基本盘
当前年份是 {G.today()[:4]} 年，涉及年份时一律用 {G.today()[:4]}。
目标问题（读者会这样问 AI）：{outline['target_question']}
文章类型：{outline['type']}
品牌：{b['name']}（{b.get('industry','')}）

## 必须使用的已核实事实（不得改动数值，不得编造新数据）
{facts}

## 竞品纪律
{comp_rule}

## 章节骨架
{secs}

## {R_OPEN}

## {R_FMT}

## {R_LANG}

## {R_SPEC}

## {R_GEO}

## 硬性要求（按此优先级，冲突时上面的赢）
**真实性 > 结构完整性 > 篇幅。**

- 正文不少于 {req['min_words']} 词，H2 小节 ≥ {req['min_h2']} 个
- 具备条件就写：一句可整句摘走的定义句、一个对比、一个编号步骤。
  这些是**可用的手段**不是必交的作业——材料支撑不了就别硬凑
- **数字规则（最重要的一条）**：
  1. 文中出现的每一个数字，都必须能在上面「已核实事实」里逐字找到
  2. 某处需要数字而事实里没有 → 写「（待补：xx 的具体数值）」，
     **不许估算，不许用「约/大约/业内普遍认为」蒙混**
  3. 不许为满足「要有数字」而填充。数据不足就这节写短点
- 写清楚适用与**不适用**边界，不要只说好话
- **严禁编造**：客户名、价格、资质、市场数据、竞品参数
- 任何一条要求因材料不足无法满足 → **放弃那一条**，不要用编造内容去满足它

## 输出格式
正文（Markdown）+ 文末一段「未满足项」，逐条列出哪些要求因材料不足未能满足。
直接输出，不要解释、不要前后缀。
"""
    else:
        prompt = f"""You are a long-form English writer. Follow the outline below and write an article
a reader will finish, with facts that survive checking.

## Your stance (pick one, state it at the end)
First-hand / Did the research / Know this industry / Read the material and formed a judgement.
**Never present "did the research" as "first-hand".** Do not narrate in the first person
anything you did not witness.

## Ground rules
The current year is {G.today()[:4]}. Use {G.today()[:4]} for any year reference.
Target question (this is how a reader would ask an AI): {outline['target_question']}
Article type: {outline['type']}
Brand: {b['name']} ({b.get('industry','')})

## Verified facts you must use (do not alter figures, do not invent new ones)
{facts}

## Competitor discipline
{comp_rule}

## Section outline
{secs}

## {R_OPEN}

## {R_FMT}

## {R_LANG}

## {R_SPEC}

## {R_GEO}

## Hard requirements (in priority order; when they conflict, everything above wins)
**Truth > structural completeness > length.**

- Body at least {req['min_words']} words, at least {req['min_h2']} H2 sections
- Use these when the material supports it: one definition sentence that can be lifted whole,
  one comparison, one numbered procedure. These are **available tools, not mandatory
  deliverables** — if the material cannot support one, leave it out
- **The number rule (the most important one)**:
  1. Every number in the article must be findable word-for-word in the verified facts above
  2. If a spot needs a number and the facts have none, write “(TBD: the actual figure for X)”
     and **do not estimate, do not paper over it with "around" or "industry estimates"**
  3. Do not fill in numbers to satisfy "must have numbers". Thin data means that section
     gets shorter
- State what the product is for and **what it is not for**. Do not only say good things
- **Never fabricate**: client names, prices, certifications, market data, competitor specs
- If any requirement cannot be met for lack of material, **drop that requirement** —
  never fabricate to satisfy it

## Output format
Markdown body, then a closing "Unmet requirements" section listing which requirements
could not be met for lack of material.
Output directly. No explanation, no preamble.
"""
    if angle_hint:
        prompt += (f"\n## 叙事角度（只影响怎么讲，不影响上面任何一条纪律）\n{angle_hint}\n" if zh
                   else f"\n## Narrative angle (changes only how it is told; none of the discipline above)\n{angle_hint}\n")
    # 起草一篇 2000 词长文要跑几分钟。原来写死 300s，实测有篇跑到 6 分钟被判失败，
    # 而失败信息又被上层统一报成「没有可用的 LLM API Key」——把一次超时误导成
    # 配置问题。这里抬到 600s，并且失败时把真实原因打出来。
    res = S.ask(plat, prompt, timeout=600)
    if res.get("ok"):
        return res.get("answer", "")
    G.info(f"  起草请求失败（{plat}）：{res.get('error') or '返回空正文'}")
    return ""


# ---------------------------------------------------------------- 多版本起草

# 同一篇的多个叙事角度。
#
# 为什么是「换角度」而不是「同一 prompt 跑三遍」：
# 随机改写不产生有意义的选择 —— 三个版本只是措辞不同，人选起来没有依据，
# 最后会退化成「看哪个顺眼」，等于没审。换切入角度才会让人真的比较。
#
# 为什么角度只写「怎么讲」：
# 事实纪律、竞品纪律、硬性要求、禁止编造，在 draft() 里对所有版本一视同仁。
# 多版本不是「有的版本可以松一点」，这个边界不能破。
VARIANTS = [
    ("a", "权威型",
     "以数据和标准切入：开头先给可核查的数字、行业标准或权威定义，建立可信度后再展开。"
     "适合百科词条、知乎长文、白皮书。"),
    ("b", "实用型",
     "以操作步骤切入：开头直给「怎么做」，结论和步骤前置，读者照着能动手。"
     "适合公众号、技术博客、教程类阵地。"),
    ("c", "对比型",
     "以选型对比切入：开头点明「同类方案怎么选」，用对比表建立参照系，再落到具体推荐。"
     "适合榜单类问题、选型指南。"),
]


def _variant_dir(slug: str, qid: str) -> Path:
    return G.project_dir(slug) / "assets" / "variants" / qid


def variants(slug: str, qid: str | None = None, n: int = 3,
             provider: str | None = None) -> dict:
    """同一篇出 n 个不同角度的版本，供人挑选后再发布。

    与 draft() 的分工：
      draft()    一个问题出一篇（横向铺量）
      variants() 一篇出几个角度（纵向给选择）

    qid 省略时取第一个还没有选定版本的问题。
    产物：assets/variants/<qid>/<角度id>.md，每个都跑 lint_draft 并把
    风险摘要写进文件头，让人在选之前先看到编造风险。
    """
    import sample as S

    plat = S.pick_llm(provider)
    if not plat:
        G.info("没有可用的 LLM API Key，无法起草")
        return {"ok": False, "error": "no_llm"}

    outlines = gen_outlines(slug)
    if not outlines:
        G.info("没有大纲。先跑 generate --asset outlines")
        return {"ok": False, "error": "no_outlines"}

    if qid:
        picked = [o for o in outlines if o["question_id"] == qid]
        if not picked:
            G.info(f"找不到问题 {qid}。可用的：{[o['question_id'] for o in outlines][:10]}")
            return {"ok": False, "error": "unknown_qid"}
        o = picked[0]
    else:
        o = outlines[0]
        qid = o["question_id"]

    n = max(1, min(int(n), len(VARIANTS)))
    d = _variant_dir(slug, qid)
    d.mkdir(parents=True, exist_ok=True)

    made = []
    for vid, vname, hint in VARIANTS[:n]:
        G.info(f"起草 {qid} · {vname}…")
        text = draft(slug, o, provider=provider, angle_hint=hint)
        if not text:
            G.info(f"  {vname} 生成失败（LLM 无返回），后续版本跳过")
            break
        f = d / f"{vid}.md"
        # 已被 pick 选定的版本不静默覆盖：_index.json 里的 picked 仍指向它，
        # 覆盖之后索引与实际内容分叉，而 drafts/<qid>.md 里留的还是旧文本。
        # 旧内容先另存一份，让这次覆盖有痕可查。
        if f.exists() and _is_picked(slug, qid, vid):
            f.with_suffix(".prev.md").write_text(f.read_text("utf-8"), "utf-8")
            G.info(f"  {vname} 是已选定版本，旧文另存为 {vid}.prev.md")
        f.write_text(text, "utf-8")
        made.append({"id": vid, "name": vname, "path": str(f.relative_to(G.project_dir(slug)))})

    if not made:
        return {"ok": False, "error": "all_failed"}

    # 风险检查对每个版本都跑 —— 人选之前先看到风险，而不是选完才发现
    risks = {}
    for m in made:
        try:
            risks[m["id"]] = lint_draft(slug, G.project_dir(slug) / m["path"])
        except Exception as e:  # noqa: BLE001
            risks[m["id"]] = [{"level": "warn", "msg": f"lint 失败：{e}"}]

    _write_variant_index(slug, qid, o, made, risks)

    G.info("")
    G.info(f"已起草 {len(made)} 个版本 → assets/variants/{qid}/")
    for m in made:
        r = risks.get(m["id"]) or []
        tag = "⚠ 有风险" if r else "未发现编造风险"
        G.info(f"  {m['id']}  {m['name']}   {tag}")
    G.info("")
    G.info(f"读完后选定：geo.py pick --slug {slug} --qid {qid} --variant <a|b|c>")
    return {"ok": True, "qid": qid, "variants": made, "risks": risks}


def _write_variant_index(slug: str, qid: str, outline: dict,
                         made: list, risks: dict) -> None:
    """写版本索引。留痕：出过哪几版、各有什么风险、最终选了哪个。"""
    p = _variant_dir(slug, qid) / "_index.json"
    prev = {}
    if p.exists():
        try:
            prev = json.loads(p.read_text("utf-8"))
        except Exception:  # noqa: BLE001
            prev = {}
    doc = {
        "question_id": qid,
        "target_question": outline["target_question"],
        "generated_at": G.now_iso(),
        "variants": [{**m, "risks": risks.get(m["id"], [])} for m in made],
        # 重跑 variants 不清空已选结果 —— 选定是人工决定，不能被重生成覆盖
        "picked": prev.get("picked"),
    }
    p.write_text(json.dumps(doc, ensure_ascii=False, indent=1), "utf-8")


def _is_picked(slug: str, qid: str, vid: str) -> bool:
    """该版本是不是当前被 pick 选定的那一个。"""
    p = _variant_dir(slug, qid) / "_index.json"
    if not p.exists():
        return False
    try:
        return (json.loads(p.read_text("utf-8")).get("picked") or {}).get("id") == vid
    except Exception:  # noqa: BLE001
        return False


def pick(slug: str, qid: str, variant_id: str) -> dict:
    """人工选定哪个版本。选中的复制成正式初稿并留痕。

    这是「人在回路里」的落点：variants 产选择，pick 做决定。
    pick 之后才进发布流程 —— 发布链条上只认 assets/drafts/<qid>.md，
    而它只能由 pick 写出来。
    """
    # qid / variant 是直接拼进文件路径的，而 geo.py 把 CLI 参数原样透传过来。
    # 不校验的话 `--qid ../../x` 能读到项目外任意 .md，并把它写到 assets/ 之外。
    if not re.fullmatch(r"q\d{3}[-\w]*", qid or ""):
        G.info(f"非法的问题标识：{qid!r}")
        return {"ok": False, "error": "bad_qid"}
    if not re.fullmatch(r"[a-z0-9_-]{1,16}", variant_id or ""):
        G.info(f"非法的版本标识：{variant_id!r}")
        return {"ok": False, "error": "bad_variant"}

    d = _variant_dir(slug, qid)
    src = d / f"{variant_id}.md"
    if not src.exists():
        avail = sorted(x.stem for x in d.glob("*.md")) if d.exists() else []
        G.info(f"没有版本 {variant_id}。该问题下可用：{avail or '（无，先跑 variants）'}")
        return {"ok": False, "error": "no_such_variant"}

    drafts = G.project_dir(slug) / "assets" / "drafts"
    drafts.mkdir(parents=True, exist_ok=True)
    dst = drafts / f"{qid}.md"
    body = src.read_text("utf-8")
    dst.write_text(
        f"<!-- 选定版本 {variant_id} · 由 pick 于 {G.today()} 写入 · 需人工核实所有事实后再发布 -->\n\n"
        + body, "utf-8")

    idx = d / "_index.json"
    if idx.exists():
        try:
            doc = json.loads(idx.read_text("utf-8"))
            name = next((v["name"] for v in doc.get("variants", []) if v["id"] == variant_id), "")
            doc["picked"] = {"id": variant_id, "name": name, "picked_at": G.now_iso()}
            idx.write_text(json.dumps(doc, ensure_ascii=False, indent=1), "utf-8")
        except Exception as e:  # noqa: BLE001
            G.info(f"  索引更新失败（不影响选定）：{e}")

    # 选定稿要重新过一遍编造检查：_lint.json 是快照，pick 换掉正文之后清单
    # 描述的还是上一批文本，而交付包是无条件收 assets/ 全目录的。
    try:
        rep = lint_all(slug)
        G.info(f"  初稿风险检查已刷新：{rep.get('total_issues', 0)} 项")
    except Exception as e:  # noqa: BLE001
        G.info(f"  风险检查刷新失败（不影响本次选定）：{e}")

    G.info(f"已选定 {qid} 的版本 {variant_id} → assets/drafts/{qid}.md")
    G.info("下一步：人工核实事实，然后走发布流程")
    return {"ok": True, "qid": qid, "variant": variant_id, "draft": str(dst)}


# ---------------------------------------------------------------- 初稿风险检查

FAKE_HINTS = [
    # 尾锚用 (?![A-Za-z0-9]) 而不是 \b：CJK 在 Python re 里算 \w，而「工具A是核心」
    # 正是中文句子的默认写法 —— A 后面没有词边界，\b 版本会把这类占位竞品名
    # 全部漏报（实测只命中「工具A 的」「工具A、工具B」这种带分隔符的）。
    (r"工具\s*[A-Z一二三四五六七八九十](?![A-Za-z0-9])", "出现「工具A/工具一」这类占位竞品名"),
    (r"某某|XX公司|xxx公司|示例公司", "出现占位公司名"),
    (r"(?i)\b(acme|foobar|example corp|competitor [a-z])\b", "出现占位英文品牌名"),
]


def _norm_num(s: str) -> str:
    """数字归一化：去空格与千分位逗号，全角符号转半角，便于等值比较。"""
    return (str(s).strip().replace(",", "").replace(" ", "")
            .replace("％", "%").replace("　", ""))


def lint_draft(slug: str, path: Path) -> list[dict]:
    """交付前的编造风险检查。宁可误报，也不能让编造内容进客户交付包。"""
    import re as _re

    cfg = G.load_config(slug)
    f = parse_facts(slug)
    text = path.read_text("utf-8")
    known = {cfg["brand"]["name"], *cfg["brand"].get("aliases", [])}
    known |= {c["name"] for c in cfg.get("competitors", [])}
    for c in cfg.get("competitors", []):
        known |= set(c.get("aliases", []) or [])

    issues = []
    for pat, desc in FAKE_HINTS:
        for m in _re.finditer(pat, text):
            issues.append({"level": "高", "type": "疑似编造", "detail": desc,
                           "excerpt": text[max(0, m.start() - 30):m.end() + 30].replace("\n", " ")})

    # 事实卡里没有的数字，且没标「待确认/待补」→ 需人工核
    known_values = {n["value"] for n in f.get("numbers", [])}
    known_norm = {_norm_num(v) for v in known_values}
    # 逐个数字 token 扫，不要拿「整行」当匹配单位：`[^\n|]*` 尾部贪婪会吃掉整行，
    # finditer 因此每行只产出一个匹配 —— 实测「价格是 199 元、299 元和 399 元」
    # 只报 199 元，同一行里其余编造数字全部漏报。
    for m in _re.finditer(
            r"\d[\d,\.]*\s*(?:%|％|万|亿|倍|元|美元|港币|HK\$|\$|人|家|天|小时|分钟)", text):
        val = m.group(0).strip()
        # 等值比较，不用双向子串：双向子串会把编造数字认成已核实
        # （实测 "200 元" in "1200 元" 为 True），而夸大数据正是最常见的编造形态。
        if _norm_num(val) in known_norm:
            continue
        # 「待确认」只看数字附近，不看整行：按整行判的话，行内任何位置出现
        # 「待补」都会把这一行的所有数字一起放过。
        ctx = text[max(0, m.start() - 40):m.end() + 40]
        if "待确认" in ctx or "待补" in ctx:
            continue
        issues.append({"level": "中", "type": "未核实数字",
                       "detail": f"`{val}` 不在事实卡里且未标注待确认",
                       "excerpt": ctx.replace("\n", " ").strip()[:90]})

    year = G.today()[:4]
    for m in _re.finditer(r"20\d{2}\s*年", text):
        if m.group(0).strip() != f"{year}年":
            issues.append({"level": "低", "type": "年份存疑", "detail": f"出现 {m.group(0)}，当前是 {year} 年",
                           "excerpt": text[max(0, m.start() - 25):m.end() + 25].replace("\n", " ")})
    # 同类问题合并，避免刷屏
    seen, out = set(), []
    for i in issues:
        k = (i["type"], i["detail"])
        if k in seen:
            continue
        seen.add(k)
        out.append(i)
    return out


def lint_all(slug: str) -> dict:
    d = G.project_dir(slug) / "assets" / "drafts"
    files = sorted(d.glob("*.md")) if d.exists() else []
    report = {"slug": slug, "checked_at": G.now_iso(), "files": {}}
    total = 0
    for p in files:
        iss = lint_draft(slug, p)
        report["files"][p.name] = iss
        total += len(iss)
    report["total_issues"] = total
    report["high"] = sum(1 for v in report["files"].values() for i in v if i["level"] == "高")
    G.write_json(d / "_lint.json", report) if files else None
    return report


# ---------------------------------------------------------------- 主流程

# AI 引擎来源域名（references/attribution.md 的代码实现）。
# 「常见」清单——各家 referrer 策略会变，产出的资产里都带「先核对自己日志」的说明。
AI_REFERRERS = {
    "cn": ["doubao.com", "kimi.moonshot.cn", "kimi.com", "chat.deepseek.com", "chatglm.cn",
           "yuanbao.tencent.com", "tongyi.aliyun.com", "tongyi.com", "yiyan.baidu.com",
           "metaso.cn", "n.cn", "quark.cn"],
    "global": ["chatgpt.com", "chat.openai.com", "perplexity.ai", "gemini.google.com",
               "copilot.microsoft.com", "claude.ai", "grok.com"],
}


_LOG_COUNT_SH = r"""#!/bin/sh
# AI 流量归因：在站点服务器的日志目录里跑。
#   sh log-count.sh                 # 默认当前目录
#   sh log-count.sh /var/log/nginx
#
# 三条纪律（都是实际踩出来的）：
#   1. 来源会话只看 referrer 字段、且只比**主机名**：
#      · 整行匹配会把爬虫抓取算成用户来源（ClaudeBot 的 UA 里就带 claude.ai）；
#      · 整串匹配会把自家 URL 上的 utm 值当成来源 —— 实测 242 条「AI 来源」里
#        227 条的 referer 是 https://freemodel.online/?utm_source=chatgpt.com，
#        来源其实是自己。真正的 referer 只有 15 条。utm 那条单独数。
#   2. 爬虫分 检索型 / 训练型 / 用户触发：检索型才是引用变多的前置信号，
#      训练型只是被喂进模型，混在一起看不出趋势。
#   3. 按 UA 匹配会把漏洞扫描器一起数进来（它们轮换 UA 去打 /.env、/wp-config.php）。
#      所以脚本自己报一条「疑似扫描」计数与占比 —— 噪声必须在报告里一眼可见，
#      否则交付物上写的就是「AI 抓了你的 .env」。
#
# 口径：算出来的是下界（App 内打开常不带 referer），报告写「可归因 ≥ N」。

D=${1:-.}
AIREF='__REF__'

for f in "$D"/access.log*; do
  [ -f "$f" ] || continue
  case "$f" in
    *.gz) gzip -dc "$f" 2>/dev/null ;;
    *)    cat "$f" 2>/dev/null ;;
  esac
done | awk -v refrx="$AIREF" '
function kind(u) {
  if (u ~ /OAI-SearchBot|PerplexityBot|Claude-Web|Baiduspider|YisouSpider|PetalBot/) return "检索型"
  if (u ~ /ChatGPT-User/) return "用户触发"
  if (u ~ /GPTBot|ClaudeBot|anthropic-ai|Google-Extended|Applebot-Extended|Bytespider/) return "训练型"
  return ""
}
function engine(u) {
  if (match(u, /GPTBot|OAI-SearchBot|ChatGPT-User|ClaudeBot|Claude-Web|anthropic-ai|PerplexityBot|Google-Extended|Applebot-Extended|Bytespider|Baiduspider|YisouSpider|PetalBot/))
    return substr(u, RSTART, RLENGTH)
  return ""
}
function is_scan(p) {
  return (p ~ /\/\.env|wp-config|\/\.git|\/\.ssh|secrets\.json|\/\.aws|admin\.php|xmlrpc\.php|\.sql$|\.bak$|\.old$|\.swp$|\/\.DS_Store/)
}
function host(u) {
  h = u; sub(/^[A-Za-z]+:\/\//, "", h); sub(/^\/\//, "", h)
  sub(/[:\/?#].*$/, "", h)
  return h
}
{
  if (split($0, a, "\"") < 7) next
  req = a[2]; rf = a[4]; ua = a[6]
  if (rf != "-" && rf != "") {
    h = host(rf)
    if (h != "" && tolower(h) ~ tolower(refrx)) { refs[h]++; nref++ }
  }
  p = ""
  if (req != "") { split(req, q, " "); p = q[2]; if (p == "") p = q[1] }
  if (p ~ /[?&]utm_source=/) {
    u2 = p; sub(/^.*[?&]utm_source=/, "", u2); sub(/[& ].*$/, "", u2)
    if (u2 != "" && tolower(u2) ~ tolower(refrx)) { utms[u2]++; nutm++ }
  }
  e = engine(ua)
  if (e == "") next
  cnt[kind(ua)]++; bots[e]++; nbot++
  if (p != "" && is_scan(p)) nscan++
}
END {
  printf "AI 爬虫抓取共 %d 条\n", nbot
  printf "  检索型 %d   训练型 %d   用户触发 %d\n", cnt["检索型"], cnt["训练型"], cnt["用户触发"]
  printf "\n按引擎：\n"
  for (e in bots) printf "  %-18s %6d\n", e, bots[e]
  printf "\nAI 来源会话（referer 主机名命中）共 %d 条：\n", nref
  if (nref == 0) printf "  （0 条也正常：App 内打开不带 referer，别据此说没人从 AI 过来）\n"
  for (r in refs) printf "  %-28s %6d\n", r, refs[r]
  printf "\n自报来源（URL 上的 utm_source 命中，与 referer 分开）共 %d 条：\n", nutm
  if (nutm == 0) printf "  （无。要按渠道归因就在对外链接上带 utm_source，别靠猜）\n"
  for (u2 in utms) printf "  %-28s %6d\n", u2, utms[u2]
  printf "\n噪声检查：疑似漏洞扫描 %d 条", nscan
  if (nbot > 0) printf "（占爬虫计数 %.0f%%）", 100 * nscan / nbot
  printf "\n  这些不是 AI：扫描器轮换 UA 去打 /.env、/wp-config.php。占比高就说明\n"
  printf "  爬虫计数被污染了，报告里不能直接引用这个数。\n"
}
'
"""


def gen_attribution(slug: str) -> dict[str, str]:
    """AI 流量归因配置包：日志分析脚本 + GA4 渠道组正则 + 接入说明。"""
    cfg = G.load_config(slug)
    market = cfg.get("market", "cn")
    doms = (AI_REFERRERS["cn"] if market == "cn"
            else AI_REFERRERS["global"] if market == "global"
            else AI_REFERRERS["cn"] + AI_REFERRERS["global"])
    rx = "|".join(d.replace(".", r"\.") for d in doms)
    ga4 = (f"AI 来源渠道组（GA4 · 来源 匹配正则）\n\n{rx}\n\n"
           "配置路径：管理 → 数据显示 → 渠道组 → 新建渠道「AI 引擎」，条件：来源 与正则匹配。\n"
           "注意：测到的是下界（App 内打开常不带 referrer），报告口径写「可归因的 AI 会话 ≥ N」。\n"
           "如果站点根本没装分析 SDK（隐私页往往明写了这一点），这一条不适用，只用日志那条；\n"
           "装之前先看隐私页怎么写的 —— 交付物里的承诺不能自己打自己。\n")
    # awk 里这个正则是「字符串当动态正则」，\. 会触发 "escape sequence treated as
    # plain ." 警告，用 [.] 写等价的字面点，警告没了、语义还更准。
    log_cmd = _LOG_COUNT_SH.replace("__REF__", rx.replace(r"\.", "[.]"))
    readme = ("# AI 流量归因接入说明\n\n"
              "1. `log-count.sh`：**主路**。在站点服务器上跑，统计 AI 爬虫抓取量与 AI 来源会话。\n"
              "2. `ga4-channel.txt`：站点有 GA4 时才用（没有就别装，见下）。\n"
              "3. 转化事件（注册/留资/下单）里保存来源快照：点击 ID > UTM > referrer > 直接/未知\n\n"
              "纪律（详见 references/attribution.md）：\n"
              "- **只跑日志，不装第三方分析** 也能出数：日志里有 referer、有爬虫 UA、有按周趋势。\n"
              "  装 GA4 会与「本站无 analytics SDK」这类隐私承诺冲突，先核对隐私页再决定。\n"
              "- 爬虫计数会被轮换 UA 的漏洞扫描器污染，脚本会自己报「疑似扫描」占比；\n"
              "  占比高时那个数不能进报告。\n"
              "- referrer 清单是「常见」口径，先在自己日志里核对；测到的是下界，不外推；\n"
              "  公开内容不堆 UTM（带参 URL 会稀释规范 URL 的引用份额）。\n")
    return {"ga4-channel.txt": ga4, "log-count.sh": log_cmd, "README.md": readme}


def gen_deploy_md(slug: str) -> str:
    """给开发同学的上线清单。每步写清「放到哪 / 别放到哪 / 怎么算做完」。

    跟着项目生成，不是一份通用模板：路径、文件名、验收命令都取自这个项目
    assets/ 下**实际存在**的文件（不是「应该生成」的清单——那样会把没生成的
    也列上去，等于让人找一个不存在的文件）。

    验收项一律落到「你能亲眼看到的响应」或「看板里能跑的检查」上。
    写「确认配置正确」这种话等于没写。"""
    cfg = G.load_config(slug)
    b = cfg["brand"]
    name = b["name"]
    site = (b.get("site") or "").rstrip("/")
    market = cfg.get("market", "cn")
    has_site = G.has_site(cfg)
    adir = G.project_dir(slug) / "assets"
    have = {p.relative_to(adir).as_posix() for p in adir.rglob("*") if p.is_file()} \
        if adir.exists() else set()

    L = [f"# {name} · 上线部署清单", ""]
    if not has_site:
        L += ["这个项目没有自有网站，所以 llms.txt 与 JSON-LD 不适用"
              "（它们必须挂在自有域名下才有意义），本站不用做。", "",
              "要做的只有外部阵地那部分：内容照大纲写在平台侧发布，"
              "归因包接进自己的统计工具。做完回到看板跑一次验收。", "",
              "## 归因配置", "",
              "- `attribution/ga4-channel.txt`：在 GA4 建「AI 引擎」渠道组，匹配正则照抄",
              "- `attribution/log-count.sh`：你的服务器有 access.log 的话，本机能跑就按周统计",
              "- 纪律：测到的 AI 流量是下界，报告口径写「可归因的 AI 会话 ≥ N」，不外推",
              "", "## 验收", "",
              "回看板跑一次完整周期，系统会重抓并自动判定哪些工单闭环。", ""]
        return "\n".join(L)

    L += [
        "要把这份清单做到「引擎真的能读到」为止，不是把文件传上去就算完。",
        "每一步下面都写了验收标准——做完一步勾一步，最后回看板跑一次验收，",
        "系统重抓线上页面自动判定，不用谁来口头确认。", "",
        "## 一、先决条件", "",
        f"- 站点已上线，外网可访问：{site}",
        "- 你能改服务器 / CDN / 托管平台的配置",
        "- robots.txt 没有封禁 AI 爬虫（GPTBot / ClaudeBot / PerplexityBot 等）",
        "- 站点若在 CDN 或 WAF 后面：这些 UA 没有被拦。"
        "**浏览器能打开不代表爬虫能**——WAF 常见做法是只拦带工具标记的 UA，"
        "站长自己看不出来。体检里「WAF/CDN 差异封锁」那条查的就是这个", "",
        "## 二、要传的文件", "",
        "| 文件 | 传到哪 | 谁用 |", "|---|---|---|",
    ]
    rows = [
        ("assets/llms.txt", f"站点根目录，即 {site}/llms.txt 能直接打开", "开发"),
        ("assets/llms.en.txt", f"站点根目录（英文站有独立域名就放那个站）", "开发"),
        ("assets/jsonld/*.json", "按页面类型贴进该页的 `<head>`", "开发"),
        ("assets/snippets/definition.zh.html", "首屏口号下方", "开发"),
        ("assets/snippets/definition.en.html", "英文站首屏口号下方", "开发"),
        ("assets/snippets/faq.zh.html", "FAQ 页或首页 FAQ 段", "开发"),
        ("assets/snippets/faq.en.html", "英文站 FAQ 段", "开发"),
        ("assets/attribution/ga4-channel.txt", "GA4 渠道组配置（照抄正则）", "开发/运营"),
        ("assets/attribution/log-count.sh", "服务器上跑，统计 AI 来源与 AI 爬虫抓取", "开发"),
        ("assets/outlines/*.md", "不部署，交给内容同学", "内容"),
        ("assets/drafts/*.md", "不部署，人工核实后才发", "内容"),
    ]
    for f, where, who in rows:
        rel = f[len("assets/"):]
        if rel.endswith("*.json") or rel.endswith("*.md"):
            top = rel.replace("/*.", "/")
            if not any(x.startswith(top) for x in have):
                continue
        elif rel not in have:
            continue
        L.append(f"| `{f}` | {where} | {who} |")

    L += ["", "## 三、逐步做", ""]
    step = 0

    if "llms.txt" in have:
        step += 1
        L += [
            f"### {step}. llms.txt —— 官方事实索引", "",
            f"**放哪**：站点根目录。做完之后 {site}/llms.txt 直接打开就是文件本身。",
            "",
            "**别放**：`/static/`、`/assets/`、或任何需要重写规则绕一圈才能访问的目录。",
            "",
            "**验收**：",
            "",
            f"1. 浏览器打开 {site}/llms.txt，第一行应当是 `# {name}`，"
            "整页是纯文本，**不是网页**。",
            "2. 最常踩的一个坑：SPA 或托管平台把所有路径都重写到 index.html，"
            "于是 `/llms.txt` 返回 200，内容是首页 HTML。看着「能访问」，"
            "引擎拿到的却是一份网页——它只会当网页解析，索引等于没建。",
            "   修法：加一条静态文件例外，让磁盘上真实存在的文件先于 catch-all 路由匹配。",
            "3. 文件里列的那些链接必须都能打开（404 的条目等于给了引擎一个死链接）。"
            "看板体检会抽样验证里面的链接，以及那几条是否被 robots 封了。",
            "",
        ]

    jsonld_rows = [
        ("organization.json", "首页 / 关于页"),
        ("software-application.json", "产品页（有产品实体才生成）"),
        ("article.json", "文章页"),
        ("breadcrumb.json", "所有内容页"),
        ("faq-page.json", "有 FAQ 段的页面"),
    ]
    present = [(fn, w) for fn, w in jsonld_rows if f"jsonld/{fn}" in have]
    if present:
        step += 1
        L += [
            f"### {step}. JSON-LD —— 结构化数据", "",
            "`assets/jsonld/` 里是按页面类型分好的，**不是往站点根目录传的文件**，"
            "是整段贴进对应页面的 `<head>`：",
            "",
            "| 文件 | 贴到哪 |",
            "|---|---|",
        ]
        L += [f"| `{fn}` | {w} |" for fn, w in present]
        L += [
            "",
            "贴法（注意外层要包 `<script type=\"application/ld+json\">`，"
            "不包的话搜索引擎读不到）：",
            "",
            "```html",
            "<script type=\"application/ld+json\">",
            "{ ... 这里放 json 文件的完整内容 ... }",
            "</script>",
            "```",
            "",
            "**验收**：改完之后用 Google 的 Rich Results Test 或 schema.org 校验器"
            "跑一遍线上 URL，没有报错。看板体检的「理解层」也会检查 JSON-LD 类型是否齐全。",
            "",
        ]

    if any(x.startswith("snippets/") for x in have):
        step += 1
        L += [
            f"### {step}. 定义块与 FAQ 块 —— 页面上要真的看得见", "",
            "定义块放首屏口号下方——口号负责转化，这一段负责被 AI 摘走。",
            "",
            "**关键纪律**：这段文字必须与官网首屏、关于页、JSON-LD 的 `description`、"
            "`llms.txt` 四处**逐字一致**。口径不一致是 AI 描述品牌漂移的头号原因。",
            "",
            "FAQ 块的答案**必须在静态 HTML 里可见**——用 JS 渲染出来的内容是抓不到的。",
            "",
            "**验收**：",
            "",
            "1. 打开线上页面 → 右键「查看网页源代码」（不是「检查元素」，那个看的是"
            "渲染后的 DOM）→ 搜定义句，**能搜到**才算数。",
            "2. 四处定义句逐字一致。看板「品牌事实库」页有这条纪律的提醒。",
            "",
        ]
    if any(x.startswith("attribution/") for x in have):
        step += 1
        L += [
            f"### {step}. 归因包 —— 把闭环接到自己的数据里", "",
            "1. GA4：管理 → 数据显示 → 渠道组 → 新建渠道「AI 引擎」，"
            "正则照抄 `attribution/ga4-channel.txt`。",
            "2. 服务器有 access.log 的话，把 `log-count.sh` 拷上去按周跑一次。",
            "   AI 爬虫抓取量变多通常**先于**被引用变多，是前置信号。",
            "3. 转化事件（注册 / 留资 / 下单）里存下来源快照："
            "点击 ID > UTM > referrer > 直接/未知。",
            "",
            "**验收**：GA4 里「AI 引擎」渠道组能看到会话数。"
            "数字很小是正常的——App 内打开常常不带 referrer，测到的是**下界**，"
            "报告里就写「可归因的 AI 会话 ≥ N」，不要外推成总量。",
            "",
        ]
    missing = [k for k in ("snippets", "attribution")
               if not any(x.startswith(k + "/") for x in have)]
    if step and missing:
        L += [f"（这一期没生成 {'、'.join(missing)}；要补就跑 "
              f"`geo.py generate --slug {slug} --asset {','.join(missing)}`。）", ""]

    L += [
        "## 四、上线后怎么复核", "",
        "回到看板跑一次完整周期（设置 → 运行任务 → 跑完整一期），它会重抓线上页面，",
        "自动判定哪些工单真的闭环；之前达标现在不达标的会自动打回，不会被忽略。",
        "",
        "无法程序判定的（比如百科词条有没有过审）会标「待人工」，确认后手动标记。",
        "",
        "节奏建议：**页面体检每周，AI 答案采样每两周或每月**。"
        "采样有成本、指标本身有噪声，跑太密看不出信号，跑太疏发现问题太晚。",
        "",
        "## 五、几个会白干的坑", "",
        "- **文件传上去了但路由不认**：见第 1 步第 2 条，SPA/托管重写的经典坑。",
        "- **CDN 缓存了旧的 404**：传完文件刷一下缓存，否则爬虫拿到的还是 404。",
        "- **robots.txt 一边给索引一边拦抓取**：llms.txt 里指向的页面如果被 "
        "`Disallow` 封了 AI 爬虫，等于自相矛盾。体检会把这种条目单独列出来。",
        "- **定义句改了四处只改了两处**：这是最高频的一类返工，改之前先搜全站。",
        "- **内容里堆 UTM**：带参 URL 会稀释规范 URL 的引用份额，公开内容不要挂参数。",
        "",
    ]
    return "\n".join(L)


ASSETS = ["llms", "jsonld", "snippets", "outlines", "attribution"]


def run(slug: str, which: list[str] | None = None, with_draft: bool = False,
        draft_limit: int = 3, redraft: bool = False) -> dict:
    cfg = G.load_config(slug)
    market = cfg.get("market", "cn")
    adir = G.project_dir(slug) / "assets"
    which = which or ASSETS
    made: list[str] = []
    # llms.txt 与 JSON-LD 必须挂在自有域名下才有意义，无站点项目跳过；
    # 大纲/片段/归因这些"内容与度量"资产照常产出——它们落到外部阵地上
    if not G.has_site(cfg):
        skipped = [w for w in which if w in ("llms", "jsonld")]
        if skipped:
            G.info(f"无自有网站：跳过 {'/'.join(skipped)}（需部署到自有域名根目录/页面 head）")
        which = [w for w in which if w not in ("llms", "jsonld")]

    if "llms" in which:
        (adir).mkdir(parents=True, exist_ok=True)
        if market in ("cn", "both"):
            (adir / "llms.txt").write_text(gen_llms_txt(slug, "zh"), "utf-8")
            made.append("assets/llms.txt")
        if market in ("global", "both"):
            (adir / "llms.en.txt").write_text(gen_llms_txt(slug, "en"), "utf-8")
            made.append("assets/llms.en.txt")

    if "jsonld" in which:
        d = adir / "jsonld"
        d.mkdir(parents=True, exist_ok=True)
        for name, obj in gen_jsonld(slug).items():
            (d / f"{name}.json").write_text(json.dumps(obj, ensure_ascii=False, indent=2), "utf-8")
            made.append(f"assets/jsonld/{name}.json")

    if "snippets" in which:
        d = adir / "snippets"
        d.mkdir(parents=True, exist_ok=True)
        for lang in (["zh"] if market == "cn" else ["en"] if market == "global" else ["zh", "en"]):
            (d / f"definition.{lang}.html").write_text(gen_definition_block(slug, lang), "utf-8")
            (d / f"faq.{lang}.html").write_text(gen_faq_block(slug, lang), "utf-8")
            made += [f"assets/snippets/definition.{lang}.html", f"assets/snippets/faq.{lang}.html"]

    if "attribution" in which:
        d = adir / "attribution"
        d.mkdir(parents=True, exist_ok=True)
        for name, body in gen_attribution(slug).items():
            # .sh 走 write_bytes：Windows 上 write_text 会把 \n 翻成 \r\n，
            # 首行变成 "#!/bin/sh\r"，拷到服务器执行报 bad interpreter。
            if name.endswith(".sh"):
                (d / name).write_bytes(body.encode("utf-8"))
            else:
                (d / name).write_text(body, "utf-8")
            made.append(f"assets/attribution/{name}")

    outlines = []
    if "outlines" in which:
        d = adir / "outlines"
        d.mkdir(parents=True, exist_ok=True)
        outlines = gen_outlines(slug)
        for o in outlines:
            en = o["market"] == "global"
            req = o["requirements"]
            if en:
                body = [f"# Content outline · {o['target_question']}", "",
                        f"- Question ID: `{o['question_id']}` | Market: global | Type: {o['type']}",
                        "", "## Title candidates (relevance r=0.432 — the title must carry the question's own words)", ""]
                body += [f"{i+1}. {t}" for i, t in enumerate(o["title_candidates"])]
                body += ["", "## Section outline", ""]
                body += [f"{i+1}. {s}" for i, s in enumerate(o["sections"])]
                body += ["", "## Hard requirements", "",
                         f"- Body at least {req['min_words']} words, at least {req['min_h2']} H2 sections",
                         f"- Evidence: {req['evidence']}", ""]
                facts_head = "## Verified facts available"
            else:
                body = [f"# 内容大纲 · {o['target_question']}", "",
                        f"- 目标问题 ID：`{o['question_id']}` ｜ 市场：{o['market']} ｜ 类型：{o['type']}",
                        "", "## 标题候选（对题性 r=0.432，标题必须含问题原词）", ""]
                body += [f"{i+1}. {t}" for i, t in enumerate(o["title_candidates"])]
                body += ["", "## 章节骨架", ""]
                body += [f"{i+1}. {s}" for i, s in enumerate(o["sections"])]
                body += ["", "## 硬性要求", "",
                         f"- 正文 ≥ {req['min_words']} 词，H2 ≥ {req['min_h2']} 个",
                         f"- 必备抽取块：{'、'.join(req['must_have_blocks'])}",
                         f"- 列表密度 {req['list_density']}",
                         f"- 证据：{req['evidence']}", ""]
                facts_head = "## 可用的已核实事实"
            if o["facts_to_use"]:
                body += [facts_head, ""] + [f"- {x}" for x in o["facts_to_use"]] + [""]
            (d / f"{o['question_id']}.md").write_text("\n".join(body), "utf-8")
        made.append(f"assets/outlines/（{len(outlines)} 份）")
        G.write_json(adir / "outlines" / "_index.json", outlines)

    if with_draft and outlines:
        d = adir / "drafts"
        d.mkdir(parents=True, exist_ok=True)
        # 「一个 Key 都没有」是全局条件，先判一次；单篇失败则继续。
        # 原来两种情况共用一句 break：一批 27 篇里只要有一篇拿回空（限流、超时、
        # 单次 API 错），后面全部静默不写 —— 目录看着像「跑完了」，实际只出了前几篇。
        import sample as _S
        if not _S.pick_llm():
            G.info(f"  没有可用的 LLM API Key（候选链：{'/'.join(_S.LLM_PREFS)}），整批跳过起草")
        else:
            failed: list[str] = []
            for o in outlines[:draft_limit]:
                qid_o = o["question_id"]
                dst = d / f"{qid_o}.md"
                # pick 选定的人工稿也落在同一个路径上。无条件覆盖会把它冲掉，而且
                # 没有任何备份 —— 发布/交付链只认这个文件，_index.json 里的 picked
                # 却还指向已被替换的文本。
                if dst.exists() and "由 pick" in dst.read_text("utf-8")[:200]:
                    G.info(f"  跳过 {qid_o}：已有人工选定稿（要重生成先删掉它）")
                    made.append(f"assets/drafts/{qid_o}.md")
                    continue
                # 已有初稿默认跳过：27 篇里挂了一篇，重跑只为补那一篇，
                # 不该把另外 26 篇用 27 次调用重写一遍。要整批重写就删掉 drafts/*.md
                # 或调用时给 redraft=True（命令行没开这个开关，故意的 —— 默认行为
                # 必须是「补缺」而不是「覆盖」）。
                if dst.exists() and not redraft:
                    G.info(f"  跳过 {qid_o}：已有初稿（要重写先删掉它）")
                    made.append(f"assets/drafts/{qid_o}.md")
                    continue
                G.info(f"起草 {qid_o} · {o['target_question'][:30]}…")
                try:
                    text = draft(slug, o)
                except Exception as e:  # noqa: BLE001
                    G.info(f"  {qid_o} 起草抛错，跳过：{type(e).__name__}: {e}")
                    text = ""
                if text:
                    dst.write_text(
                        f"<!-- 初稿，需人工核实所有事实后再发布 · {G.today()} -->\n\n" + text, "utf-8")
                    made.append(f"assets/drafts/{qid_o}.md")
                else:
                    failed.append(qid_o)
                    G.info(f"  {qid_o} 没拿到正文，继续下一篇（不中断整批）")
            if failed:
                G.info(f"  本批 {len(failed)} 篇没出稿：{'、'.join(failed)}。"
                       f"重跑同一条命令即可补上（已有初稿会跳过，只补缺的）")
        rep = lint_all(slug)
        if rep.get("total_issues"):
            G.info(f"初稿风险检查：{rep['total_issues']} 项（高风险 {rep['high']} 项）"
                   f" → assets/drafts/_lint.json。**发布前必须人工核实**")

    # 部署清单在最后生成：它要按 assets/ 下实际存在的文件来列（见 gen_deploy_md）
    (adir).mkdir(parents=True, exist_ok=True)
    (adir / "DEPLOY.md").write_text(gen_deploy_md(slug), "utf-8")
    made.append("assets/DEPLOY.md")

    index = {"slug": slug, "generated_at": G.now_iso(), "market": market, "assets": made}
    G.write_json(adir / "index.json", index)
    G.info(f"生成 {len(made)} 项资产 → {adir}")
    return index
